DEBUG = False
SECRET_KEY = ''  # Key for forms (can be anything)
SQLALCHEMY_DATABASE_URI = ''  # URI for SQL Database
STEAM_API_KEY = ''  # http://steamcommunity.com/dev/apikey
UPLOADED_WORKSHOPZIPS_DEST = ''  # Folder for zips to be uploaded to
UPLOADED_MODIMAGES_DEST = ''  # Folder for images to be uploaded to (current unused)
OUTPUT_FOLDER_LOCATION = ''  # Save location for mod files
VPK_BINARY_PATH = ''  # VPK binaries
SENTRY_ENABLED = True
SENTRY_DSN = ''  # Sentry API key for logging errors