"""Add package and package download tables.

Revision ID: 1e56723601b7
Revises: 3642ec8d5d7c
Create Date: 2014-07-23 21:47:59.851171

"""

# revision identifiers, used by Alembic.
revision = '1e56723601b7'
down_revision = '3642ec8d5d7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('defindex', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['defindex'], ['tf2_schema.defindex'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('downloaded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['mod_package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_download')
    op.drop_table('mod_package')
    ### end Alembic commands ###
