"""Add signed_in field, to allow tracking whether a user is signed in (used for tracking non-signed in authors)

Revision ID: 21f6eb9a23f9
Revises: 4e94d943701e
Create Date: 2014-08-10 14:47:55.182898

"""

# revision identifiers, used by Alembic.
revision = '21f6eb9a23f9'
down_revision = '4e94d943701e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signed_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signed_in')
    ### end Alembic commands ###
