"""Add Mod tags.

Revision ID: 297aa7f4c6aa
Revises: 21f6eb9a23f9
Create Date: 2014-09-21 21:27:05.377418

"""

# revision identifiers, used by Alembic.
revision = '297aa7f4c6aa'
down_revision = '21f6eb9a23f9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bg_num', sa.Integer(), nullable=True),
    sa.Column('css', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_tag',
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], )
    )
    op.drop_column(u'mods', 'license')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'mods', sa.Column('license', mysql.VARCHAR(length=16), nullable=True))
    op.drop_table('mod_tag')
    op.drop_table('tags')
    ### end Alembic commands ###
