"""Update mod workshop_id type to unsigned integer

Revision ID: 2b597958273b
Revises: 7f0e7d496f6
Create Date: 2020-08-17 01:00:03.055399

"""

# revision identifiers, used by Alembic.
revision = '2b597958273b'
down_revision = '7f0e7d496f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mods', 'workshop_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=mysql.INTEGER(display_width=11,unsigned=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mods', 'workshop_id',
               existing_type=mysql.INTEGER(display_width=11,unsigned=True),
               type_=mysql.INTEGER(display_width=11))
    ### end Alembic commands ###
