"""Add Steam fetch timeout

Revision ID: 2ebc6e1081be
Revises: 35c29e829e42
Create Date: 2014-07-31 23:40:33.757223

"""

# revision identifiers, used by Alembic.
revision = '2ebc6e1081be'
down_revision = '35c29e829e42'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mod_author', 'mod_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('mod_author', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('users', sa.Column('next_steam_check', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'next_steam_check')
    op.alter_column('mod_author', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('mod_author', 'mod_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
