"""Add mod description

Revision ID: 347d18296575
Revises: 1e56723601b7
Create Date: 2014-07-24 16:36:29.505033

"""

# revision identifiers, used by Alembic.
revision = '347d18296575'
down_revision = '1e56723601b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mods', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mods', 'description')
    ### end Alembic commands ###
