"""Add bodygroup, equip_region and class_model mod tables.

Revision ID: 4109faaa8328
Revises: 161d3f94e40e
Create Date: 2014-07-08 01:10:08.777120

"""

# revision identifiers, used by Alembic.
revision = '4109faaa8328'
down_revision = '161d3f94e40e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_bodygroup',
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('bodygroup', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bodygroup'], ['tf2_bodygroups.bodygroup'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], )
    )
    op.create_table('mod_classmodel',
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('model_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['tf2_class.class_name'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('mod_id', 'class_name')
    )
    op.create_table('mod_equipregion',
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('equip_region', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['equip_region'], ['tf2_equip_regions.equip_region'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_equipregion')
    op.drop_table('mod_classmodel')
    op.drop_table('mod_bodygroup')
    ### end Alembic commands ###
