"""Add inactive option to remove TF2 item from search

Revision ID: 4527cf3899ec
Revises: 297aa7f4c6aa
Create Date: 2014-10-22 14:03:08.123864

"""

# revision identifiers, used by Alembic.
revision = '4527cf3899ec'
down_revision = '297aa7f4c6aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tf2_schema', sa.Column('inactive', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tf2_schema', 'inactive')
    ### end Alembic commands ###
