"""Initial pass

Revision ID: 4db12e0c5745
Revises: None
Create Date: 2014-07-05 15:30:34.596840

"""

# revision identifiers, used by Alembic.
revision = '4db12e0c5745'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=256, collation='utf8_swedish_ci'), nullable=True),
    sa.Column('profile_url', sa.String(length=128), nullable=True),
    sa.Column('avatar_small', sa.String(length=128), nullable=True),
    sa.Column('avatar_medium', sa.String(length=128), nullable=True),
    sa.Column('avatar_large', sa.String(length=128), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('user_class', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
