"""Add deleted field to mod packages

Revision ID: 4e94d943701e
Revises: 3d8536445a43
Create Date: 2014-08-06 00:56:55.856466

"""

# revision identifiers, used by Alembic.
revision = '4e94d943701e'
down_revision = '3d8536445a43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod_package', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mod_package', 'deleted')
    ### end Alembic commands ###
