"""Add defindex and hiding of download to Mod table

Revision ID: 7f0e7d496f6
Revises: 4527cf3899ec
Create Date: 2014-10-30 01:31:03.986114

"""

# revision identifiers, used by Alembic.
revision = '7f0e7d496f6'
down_revision = '4527cf3899ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mods', sa.Column('defindex', sa.Integer(), nullable=True))
    op.add_column('mods', sa.Column('hide_downloads', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mods', 'hide_downloads')
    op.drop_column('mods', 'defindex')
    ### end Alembic commands ###
